# Generated by Django 3.1.2 on 2020-11-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rareuser',
            name='active',
        ),
    ]
