# Generated by Django 3.1.3 on 2020-11-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_postreaction_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='image_url',
            field=models.ImageField(height_field=60, upload_to='emojis/', width_field=60),
        ),
    ]
