# Generated by Django 3.1.3 on 2020-11-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_remove_rareuser_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rareuser',
            old_name='profile_img_url',
            new_name='profile_image_url',
        ),
    ]
