# Generated by Django 3.1.3 on 2020-11-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_auto_20201117_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='image_url',
            field=models.ImageField(upload_to='emojis/'),
        ),
    ]
